### ISSUE TITLE
Installing exposes all scripts in bin globally

### ISSUE THREAD

**Issue by jjatria** [JJ/raku-ukr-mod-data#36]
Doing `zef install Data::UkraineWar::MoD` will take the scripts in `bin` and install them in the PATH:

```
6 bin/ scripts [commit-push.sh index.js ukr-mod-scrape-local.raku scrape.py ukr-mod-scrape.raku plot-pairs.R] installed to:
.../install/share/perl6/site/bin
```

Some of those seem _very_ local to this distribution, like `commit-push.sh`, which does

```
git config --global user.email "jjmerelo@gmail.com"
git config --global user.name "UkrModDataBot"
git commit -am "[🤖] $1"
```

Maybe they can be moved to `tools`, as suggested in [Matthew Stuckwisch's recent talk at TPRC](https://youtu.be/G2eDeSRZ6p8?t=729)? Or removed from the distribution tarball before release?

**Comment by JJ** [comment]
Absolutely and totally right. `scripts` might be another option
